import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";  // Assuming you have this component
import Sidebar from "@/components/Sidebar";  // Assuming you have this component
import Footer from "@/components/Footer";  // Assuming you have this component
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="fixed-layout">
          {/* Header */}
          <Header />

          {/* Sidebar */}
          <Sidebar />

          {/* Main Content */}
          <main className="main-content">
            {children}
          </main>

          {/* Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
